version: 2
jobs:
  build:
    macos:
      xcode: "10.0.0"
    working_directory: ~/seaglass
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: Create Upload Directory
          command: mkdir -p /tmp/upload
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Install CocoaPods
          command: pod install --verbose
      - run:
          name: Build Seaglass
          command: |
            fastlane build_and_release
      - store_artifacts:
          path: /tmp/seaglass/upload
          destination: /
